{
  "formatVersion": "1.1",
  "component": {
    "group": "com.socdm.d.adgeneration",
    "module": "adg-googleads-extra",
    "version": "2.26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adg-googleads-extra-2.26.0.aar",
          "url": "adg-googleads-extra-2.26.0.aar",
          "size": 7947,
          "sha512": "420bb1568811488d1b81be3b1cdeeb2d9073efad268eda09550af44c3dd261a5f7970eb56735a676147f131c310de14ec790260654ca409767ec3ef823598ff1",
          "sha256": "1af893d722e37f00820e302cab4545db5c9bb1cfe0e1ba0432dde603a67bcee8",
          "sha1": "60e9cd3801faf324ed070d66740df85d5c1a3d6c",
          "md5": "acebd111f2d90831bc2ec728be60a152"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adg-googleads-extra-2.26.0.aar",
          "url": "adg-googleads-extra-2.26.0.aar",
          "size": 7947,
          "sha512": "420bb1568811488d1b81be3b1cdeeb2d9073efad268eda09550af44c3dd261a5f7970eb56735a676147f131c310de14ec790260654ca409767ec3ef823598ff1",
          "sha256": "1af893d722e37f00820e302cab4545db5c9bb1cfe0e1ba0432dde603a67bcee8",
          "sha1": "60e9cd3801faf324ed070d66740df85d5c1a3d6c",
          "md5": "acebd111f2d90831bc2ec728be60a152"
        }
      ]
    }
  ]
}
