{
  "formatVersion": "1.1",
  "component": {
    "group": "com.socdm.d.adgeneration",
    "module": "adg-admob-mediation",
    "version": "2.29.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "adg-admob-mediation-2.29.1.aar",
          "url": "adg-admob-mediation-2.29.1.aar",
          "size": 14023,
          "sha512": "5e59a3298cff76617fea026c3ab8c51f05b2f3d3bd4a6a48cc36e7ec8a3c401e3d2f55b9275ba0b152e2ec27d3f0b63c671ca50a3d2ddd98f9c339aadd0cf6e3",
          "sha256": "ef2e8bb92797b1eb32921f01e7469ac89a2d31debb9554be03ddb8b3b4b0a7cc",
          "sha1": "daef3d5ea2453287fe87e4cfac14b7c955260299",
          "md5": "2d179a96708caf28675b82ce9ffd2a0a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.3.0"
          }
        },
        {
          "group": "com.socdm.d.adgeneration",
          "module": "adg",
          "version": {
            "requires": "2.29.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "adg-admob-mediation-2.29.1.aar",
          "url": "adg-admob-mediation-2.29.1.aar",
          "size": 14023,
          "sha512": "5e59a3298cff76617fea026c3ab8c51f05b2f3d3bd4a6a48cc36e7ec8a3c401e3d2f55b9275ba0b152e2ec27d3f0b63c671ca50a3d2ddd98f9c339aadd0cf6e3",
          "sha256": "ef2e8bb92797b1eb32921f01e7469ac89a2d31debb9554be03ddb8b3b4b0a7cc",
          "sha1": "daef3d5ea2453287fe87e4cfac14b7c955260299",
          "md5": "2d179a96708caf28675b82ce9ffd2a0a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "adg-admob-mediation-2.29.1-sources.jar",
          "url": "adg-admob-mediation-2.29.1-sources.jar",
          "size": 19549,
          "sha512": "72a59a266f63f612637f74a7db111e75a12b9c947500979483be72ad7ff75a667fbc59f7ab7e2f2cdb377cf9e368ec45c7ac0ff3fa165f7b01ea69020d59f33c",
          "sha256": "74420f827eacb5a4ad6579e148c495ef6aa5a198a7a05c7944be569e1a8a0db7",
          "sha1": "2555918a95d871082d1e845e130fb84470e3a1c6",
          "md5": "09a110e065441f1d28f8c4b426f20046"
        }
      ]
    }
  ]
}
