{
  "formatVersion": "1.1",
  "component": {
    "group": "com.socdm.d.adgeneration",
    "module": "adg",
    "version": "2.28.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "adg-2.28.1.aar",
          "url": "adg-2.28.1.aar",
          "size": 662121,
          "sha512": "9e2053b3767fc07b0833e36886164ad6a28ea858f4e81041a9be9c1d4a09eef3f709c78806771bb137261a07889f0dfd5c1c0107247757e2573a447351c0a63d",
          "sha256": "8ea78923473d09247b2fcbd2f490598c92f08198191d81094485b34bf6396e52",
          "sha1": "67d462e71e70efba767c8cd2c5ff69916426fc37",
          "md5": "0dc55211dc80e82d45ac407c7da63df2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "adg-2.28.1.aar",
          "url": "adg-2.28.1.aar",
          "size": 662121,
          "sha512": "9e2053b3767fc07b0833e36886164ad6a28ea858f4e81041a9be9c1d4a09eef3f709c78806771bb137261a07889f0dfd5c1c0107247757e2573a447351c0a63d",
          "sha256": "8ea78923473d09247b2fcbd2f490598c92f08198191d81094485b34bf6396e52",
          "sha1": "67d462e71e70efba767c8cd2c5ff69916426fc37",
          "md5": "0dc55211dc80e82d45ac407c7da63df2"
        }
      ]
    }
  ]
}
