{
  "formatVersion": "1.1",
  "component": {
    "group": "com.socdm.d.adgeneration",
    "module": "adg",
    "version": "2.42.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "adg-2.42.1.aar",
          "url": "adg-2.42.1.aar",
          "size": 1602960,
          "sha512": "b094edb664d6a8db5dbfbf256f3b2f90fed9226d22d27ef40f2b29ad4182ee94bdb9d57a0ce119586a7129bac569feeea7bbc7ae4c9e593d9935114e943baf4b",
          "sha256": "0a44e2724d371b90019d94a201e5687213936b0f31d9b46f6c705ee34f95124f",
          "sha1": "d82aad4129a34a1d7c80ff54ed4fdb319ea17044",
          "md5": "16601933cd327d8f80e5d45cf39a7271"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "adg-2.42.1.aar",
          "url": "adg-2.42.1.aar",
          "size": 1602960,
          "sha512": "b094edb664d6a8db5dbfbf256f3b2f90fed9226d22d27ef40f2b29ad4182ee94bdb9d57a0ce119586a7129bac569feeea7bbc7ae4c9e593d9935114e943baf4b",
          "sha256": "0a44e2724d371b90019d94a201e5687213936b0f31d9b46f6c705ee34f95124f",
          "sha1": "d82aad4129a34a1d7c80ff54ed4fdb319ea17044",
          "md5": "16601933cd327d8f80e5d45cf39a7271"
        }
      ]
    }
  ]
}
