{
  "formatVersion": "1.1",
  "component": {
    "group": "com.socdm.d.adgeneration",
    "module": "adg-admob-mediation",
    "version": "2.34.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "adg-admob-mediation-2.34.0.aar",
          "url": "adg-admob-mediation-2.34.0.aar",
          "size": 14023,
          "sha512": "b3e9e0b12b1247978ecefac7f72f5a01a40fbb740ccc28be768173f5c20584e96c9442e2b45ea3041f43579e9a6b89d44e4ffececeeede9bdbaa69db49c2bf24",
          "sha256": "70727a1f11fd1f24394a0f8d2b0fc8f537261ed85cf37fbad392f88d5d8e683b",
          "sha1": "3604974087ec1669905db239189f2399cd78c6e3",
          "md5": "6852b827a49ff6cb1f8110a3ca15f5a5"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.9.0"
          }
        },
        {
          "group": "com.socdm.d.adgeneration",
          "module": "adg",
          "version": {
            "requires": "2.34.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "adg-admob-mediation-2.34.0.aar",
          "url": "adg-admob-mediation-2.34.0.aar",
          "size": 14023,
          "sha512": "b3e9e0b12b1247978ecefac7f72f5a01a40fbb740ccc28be768173f5c20584e96c9442e2b45ea3041f43579e9a6b89d44e4ffececeeede9bdbaa69db49c2bf24",
          "sha256": "70727a1f11fd1f24394a0f8d2b0fc8f537261ed85cf37fbad392f88d5d8e683b",
          "sha1": "3604974087ec1669905db239189f2399cd78c6e3",
          "md5": "6852b827a49ff6cb1f8110a3ca15f5a5"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "adg-admob-mediation-2.34.0-sources.jar",
          "url": "adg-admob-mediation-2.34.0-sources.jar",
          "size": 19549,
          "sha512": "72a59a266f63f612637f74a7db111e75a12b9c947500979483be72ad7ff75a667fbc59f7ab7e2f2cdb377cf9e368ec45c7ac0ff3fa165f7b01ea69020d59f33c",
          "sha256": "74420f827eacb5a4ad6579e148c495ef6aa5a198a7a05c7944be569e1a8a0db7",
          "sha1": "2555918a95d871082d1e845e130fb84470e3a1c6",
          "md5": "09a110e065441f1d28f8c4b426f20046"
        }
      ]
    }
  ]
}
