{
  "formatVersion": "1.1",
  "component": {
    "group": "com.socdm.d.adgeneration",
    "module": "adg",
    "version": "2.28.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "adg-2.28.2.aar",
          "url": "adg-2.28.2.aar",
          "size": 638505,
          "sha512": "0ef664d77bc50ed56df59310a64b7e23a7af1835e229edeb9a1fff6c79bd7cfa0fdafe103cf0518dd0261b7791b9c58ad99c5ebef9860bc95db3b5fd9ed489c8",
          "sha256": "71f817ff869281c551a8cbc9f1dd10f5f598dd2cd3d27b3764574df9ab32e98e",
          "sha1": "edb89beae853b19f784b28b0b9eb3dc89265ec2f",
          "md5": "8a47efa4a80928eec80e22f07b580b66"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "adg-2.28.2.aar",
          "url": "adg-2.28.2.aar",
          "size": 638505,
          "sha512": "0ef664d77bc50ed56df59310a64b7e23a7af1835e229edeb9a1fff6c79bd7cfa0fdafe103cf0518dd0261b7791b9c58ad99c5ebef9860bc95db3b5fd9ed489c8",
          "sha256": "71f817ff869281c551a8cbc9f1dd10f5f598dd2cd3d27b3764574df9ab32e98e",
          "sha1": "edb89beae853b19f784b28b0b9eb3dc89265ec2f",
          "md5": "8a47efa4a80928eec80e22f07b580b66"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "adg-2.28.2-sources.jar",
          "url": "adg-2.28.2-sources.jar",
          "size": 400207,
          "sha512": "a6d27af84bb41161f8613a32f8d716e91417c3e68e1d5c1835a6ad8e79870456fe26a896566a5c3ab575049975b8ee195ee08c766422d9b6b9dacaba3ab8e31e",
          "sha256": "19b85d9da5c969a941237df4ac5e0610866a3755026efd393d6810fffed6bb9f",
          "sha1": "173ba3e7c7eae5dc48e7a2f87db0ed28a76af1b3",
          "md5": "0171750e1982f3a91ef17a0acc433160"
        }
      ]
    }
  ]
}
