{
  "formatVersion": "1.1",
  "component": {
    "group": "com.socdm.d.adgeneration",
    "module": "adg-admob-adapter",
    "version": "24.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "adg-admob-adapter-24.9.0.aar",
          "url": "adg-admob-adapter-24.9.0.aar",
          "size": 14927,
          "sha512": "4d95b7454259011357c0e4ffee41ff5a4feee56d3f9e6ec8d8007f8e7858b9a4c31ea543ad4f7cb8aede197eedb2211a3569431d3dd7c34df2c662413daddd1a",
          "sha256": "8b59fa0b161d53577c6200228d59ea6399f6938cf473a45854ae9b55bb7279f3",
          "sha1": "cf7ca06ea04d87bbb64fc15ee6d5a9d11a3859b9",
          "md5": "6554be43dc74cbce275a406b49bfc928"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "adg-admob-adapter-24.9.0.aar",
          "url": "adg-admob-adapter-24.9.0.aar",
          "size": 14927,
          "sha512": "4d95b7454259011357c0e4ffee41ff5a4feee56d3f9e6ec8d8007f8e7858b9a4c31ea543ad4f7cb8aede197eedb2211a3569431d3dd7c34df2c662413daddd1a",
          "sha256": "8b59fa0b161d53577c6200228d59ea6399f6938cf473a45854ae9b55bb7279f3",
          "sha1": "cf7ca06ea04d87bbb64fc15ee6d5a9d11a3859b9",
          "md5": "6554be43dc74cbce275a406b49bfc928"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "adg-admob-adapter-24.9.0-sources.jar",
          "url": "adg-admob-adapter-24.9.0-sources.jar",
          "size": 11715,
          "sha512": "72f9006d189a784626f582d4b690c2dcdb29dfd00bfcbae07d5eb754301cd9d543503c9a620237e12636c985a8f94000e118a516a47d553fdf0e2a8228dd5e98",
          "sha256": "1e57e648b4ca9a78c93feac04892fcab4cb1f964d51f2a12ca678a20754ad025",
          "sha1": "2e0b66522dc6b9e3f9c6d3d37e48a4c171e5e5ee",
          "md5": "c7c8faadde7f57bb06fb58e7f8cea53c"
        }
      ]
    }
  ]
}
