{
  "formatVersion": "1.1",
  "component": {
    "group": "com.socdm.d.adgeneration",
    "module": "adg-admob-adapter",
    "version": "24.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "adg-admob-adapter-24.1.0.aar",
          "url": "adg-admob-adapter-24.1.0.aar",
          "size": 15845,
          "sha512": "5226c524bf906c8afa6e65cc01300eac03299862267a24708f3e1dbd590c97d02920daba091d290c9d8559de0b38fb7ec9c7148c60dd3f478afc26c5bd7b662e",
          "sha256": "521b8cb19ae614ac86d8af230497f89a536430e8e2e637c78b4a1411c3576ff8",
          "sha1": "7e9418da5435c823aac6ac5b6fab34727a8d22e8",
          "md5": "4d2be8a905c3fe468a889fa0f480baba"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "adg-admob-adapter-24.1.0.aar",
          "url": "adg-admob-adapter-24.1.0.aar",
          "size": 15845,
          "sha512": "5226c524bf906c8afa6e65cc01300eac03299862267a24708f3e1dbd590c97d02920daba091d290c9d8559de0b38fb7ec9c7148c60dd3f478afc26c5bd7b662e",
          "sha256": "521b8cb19ae614ac86d8af230497f89a536430e8e2e637c78b4a1411c3576ff8",
          "sha1": "7e9418da5435c823aac6ac5b6fab34727a8d22e8",
          "md5": "4d2be8a905c3fe468a889fa0f480baba"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "adg-admob-adapter-24.1.0-sources.jar",
          "url": "adg-admob-adapter-24.1.0-sources.jar",
          "size": 11715,
          "sha512": "72f9006d189a784626f582d4b690c2dcdb29dfd00bfcbae07d5eb754301cd9d543503c9a620237e12636c985a8f94000e118a516a47d553fdf0e2a8228dd5e98",
          "sha256": "1e57e648b4ca9a78c93feac04892fcab4cb1f964d51f2a12ca678a20754ad025",
          "sha1": "2e0b66522dc6b9e3f9c6d3d37e48a4c171e5e5ee",
          "md5": "c7c8faadde7f57bb06fb58e7f8cea53c"
        }
      ]
    }
  ]
}
