{
  "formatVersion": "1.1",
  "component": {
    "group": "com.socdm.d.adgeneration",
    "module": "adg-admob-mediation",
    "version": "2.26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "adg-admob-mediation-2.26.0.aar",
          "url": "adg-admob-mediation-2.26.0.aar",
          "size": 24387,
          "sha512": "1d754a94de3ea0e62f6ba31d9250ac49b846b8d828f390c12e1d3e47af84f1fea5c2f0703672bb1344627ef5fc6c9b35771fc6306b70657c4b5bc4937c5e1b38",
          "sha256": "9433a3f7ae8759f82e93623e79721dabeedd354577399f70a51ff0a7c71762d3",
          "sha1": "e0c4094935dfce4a7cd9cb4a6e8d692014ffb202",
          "md5": "8f88c50d7c80fd22a1f14ea9337d1535"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "com.socdm.d.adgeneration",
          "module": "adg",
          "version": {
            "requires": "2.26.0"
          }
        }
      ],
      "files": [
        {
          "name": "adg-admob-mediation-2.26.0.aar",
          "url": "adg-admob-mediation-2.26.0.aar",
          "size": 24387,
          "sha512": "1d754a94de3ea0e62f6ba31d9250ac49b846b8d828f390c12e1d3e47af84f1fea5c2f0703672bb1344627ef5fc6c9b35771fc6306b70657c4b5bc4937c5e1b38",
          "sha256": "9433a3f7ae8759f82e93623e79721dabeedd354577399f70a51ff0a7c71762d3",
          "sha1": "e0c4094935dfce4a7cd9cb4a6e8d692014ffb202",
          "md5": "8f88c50d7c80fd22a1f14ea9337d1535"
        }
      ]
    }
  ]
}
