{
  "formatVersion": "1.1",
  "component": {
    "group": "com.socdm.d.adgeneration",
    "module": "adg",
    "version": "2.26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "adg-2.26.2.aar",
          "url": "adg-2.26.2.aar",
          "size": 586330,
          "sha512": "63500edd2ff4808186a9ea66b156b38100736ec023c54bfac07386ec99ebb216f60b8eda186f0e9865db2edffaa513e4b5c9df617a6d524002947fb0764fc0d9",
          "sha256": "77e8eed55b0834a565b01149c8d00eda40000dc83e0c40a4dc4d9953f7033b78",
          "sha1": "0fcd6056dea7b1dda874e912f7c601b8a8fb4c19",
          "md5": "5627aea18bfe955995f7c0a54e7dc679"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "adg-2.26.2.aar",
          "url": "adg-2.26.2.aar",
          "size": 586330,
          "sha512": "63500edd2ff4808186a9ea66b156b38100736ec023c54bfac07386ec99ebb216f60b8eda186f0e9865db2edffaa513e4b5c9df617a6d524002947fb0764fc0d9",
          "sha256": "77e8eed55b0834a565b01149c8d00eda40000dc83e0c40a4dc4d9953f7033b78",
          "sha1": "0fcd6056dea7b1dda874e912f7c601b8a8fb4c19",
          "md5": "5627aea18bfe955995f7c0a54e7dc679"
        }
      ]
    }
  ]
}
