{
  "formatVersion": "1.1",
  "component": {
    "group": "com.socdm.d.adgeneration",
    "module": "adg",
    "version": "2.35.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "adg-2.35.1.aar",
          "url": "adg-2.35.1.aar",
          "size": 1238367,
          "sha512": "49926fe8596725b9862ee23bb26f01bc76bbee45eaedbec2865800a242dd13a45046e3d6ce99ea411200687b78d6b6d952205de7aef989b7a365b519213de7d1",
          "sha256": "6d944af8d788e391e71d3adeb32b1638a0b258e7f7b4b39b8793b45143c682dd",
          "sha1": "70180d372de4acdf9b07a402b2470d646583eef2",
          "md5": "2135f5ffe96597899e037da3a70b4b38"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "adg-2.35.1.aar",
          "url": "adg-2.35.1.aar",
          "size": 1238367,
          "sha512": "49926fe8596725b9862ee23bb26f01bc76bbee45eaedbec2865800a242dd13a45046e3d6ce99ea411200687b78d6b6d952205de7aef989b7a365b519213de7d1",
          "sha256": "6d944af8d788e391e71d3adeb32b1638a0b258e7f7b4b39b8793b45143c682dd",
          "sha1": "70180d372de4acdf9b07a402b2470d646583eef2",
          "md5": "2135f5ffe96597899e037da3a70b4b38"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "adg-2.35.1-sources.jar",
          "url": "adg-2.35.1-sources.jar",
          "size": 484145,
          "sha512": "c1c5ed1934de0d1d49db3e7f25646a5fd774612f6290fe0170399e146cc7c3b050d4fc4804650cc763a07eed7ec3e2adc5ff74a5bf4bb55eacf9e756c6a5bdf8",
          "sha256": "49a14207c7e5baae140927b3908b033243ce260eb2460d23612d46bb31d2853a",
          "sha1": "026d0597d9deb9b8668bd1f3e2e57e52a9c57de0",
          "md5": "c0ca14c9d3747162d70e9c66ec2b182b"
        }
      ]
    }
  ]
}
