{
  "formatVersion": "1.1",
  "component": {
    "group": "com.socdm.d.adgeneration",
    "module": "adg-admob-adapter",
    "version": "23.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adg-admob-adapter-23.0.0.aar",
          "url": "adg-admob-adapter-23.0.0.aar",
          "size": 28997,
          "sha512": "a32290bb70d47bcc9630555607d6f1fb1351d2e15bfe385091ca2dc5de27eb70a578e0c04a632a4d06d8a4b863df0ecbba521af5ada1074f6d85685991feab9f",
          "sha256": "66246c48c0d94e03b8f11ea3f9586568988fe13dc860132a4628f7be152a91a6",
          "sha1": "25cb4a18f75b857ee30b3b43046e106b2382bf8f",
          "md5": "220209e876ff8f20bcb3017000fb382d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "adg-admob-adapter-23.0.0.aar",
          "url": "adg-admob-adapter-23.0.0.aar",
          "size": 28997,
          "sha512": "a32290bb70d47bcc9630555607d6f1fb1351d2e15bfe385091ca2dc5de27eb70a578e0c04a632a4d06d8a4b863df0ecbba521af5ada1074f6d85685991feab9f",
          "sha256": "66246c48c0d94e03b8f11ea3f9586568988fe13dc860132a4628f7be152a91a6",
          "sha1": "25cb4a18f75b857ee30b3b43046e106b2382bf8f",
          "md5": "220209e876ff8f20bcb3017000fb382d"
        }
      ]
    }
  ]
}
