{
  "formatVersion": "1.1",
  "component": {
    "group": "com.socdm.d.adgeneration",
    "module": "adg",
    "version": "2.26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "adg-2.26.0.aar",
          "url": "adg-2.26.0.aar",
          "size": 609093,
          "sha512": "0e2394398a7b6a9f683a07b6462aa5194194d21c677e4fc6ddb11a9e3ca4f5c70ba96507be199a586cb5f9008b52571208599bfeb25574dccd55c64ded4d993d",
          "sha256": "dc04af8a3b6a42ff5825e3d8f8492f3bf5d1bbb6903699d7e5da206ffba46da4",
          "sha1": "33d279bc5227b39a1fc54412b5ac2fe799f9a96c",
          "md5": "7e463da916746889ad782dbf38d3706f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "adg-2.26.0.aar",
          "url": "adg-2.26.0.aar",
          "size": 609093,
          "sha512": "0e2394398a7b6a9f683a07b6462aa5194194d21c677e4fc6ddb11a9e3ca4f5c70ba96507be199a586cb5f9008b52571208599bfeb25574dccd55c64ded4d993d",
          "sha256": "dc04af8a3b6a42ff5825e3d8f8492f3bf5d1bbb6903699d7e5da206ffba46da4",
          "sha1": "33d279bc5227b39a1fc54412b5ac2fe799f9a96c",
          "md5": "7e463da916746889ad782dbf38d3706f"
        }
      ]
    }
  ]
}
