{
  "formatVersion": "1.1",
  "component": {
    "group": "com.socdm.d.adgeneration",
    "module": "adg",
    "version": "2.26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "adg-2.26.0.aar",
          "url": "adg-2.26.0.aar",
          "size": 609292,
          "sha512": "f9eb60017c1bcf707f8a64512fdedef9f72950b60ed1a3de78f43d4b2fee2b0c0076f046bef74ea70fa35ff0a5dce7f0cf520efcf8ace68eb804ff522be2d8b3",
          "sha256": "38714a8c40d86835860ffcef6c59e2800c324b7f1991db2442cd3a8b2fcce0cd",
          "sha1": "3e715abd91683ebdc3b566f6c397d65bd63a2dd8",
          "md5": "43f4fff6bb85d9054d1d123e984fc1eb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "adg-2.26.0.aar",
          "url": "adg-2.26.0.aar",
          "size": 609292,
          "sha512": "f9eb60017c1bcf707f8a64512fdedef9f72950b60ed1a3de78f43d4b2fee2b0c0076f046bef74ea70fa35ff0a5dce7f0cf520efcf8ace68eb804ff522be2d8b3",
          "sha256": "38714a8c40d86835860ffcef6c59e2800c324b7f1991db2442cd3a8b2fcce0cd",
          "sha1": "3e715abd91683ebdc3b566f6c397d65bd63a2dd8",
          "md5": "43f4fff6bb85d9054d1d123e984fc1eb"
        }
      ]
    }
  ]
}
