{
  "formatVersion": "1.1",
  "component": {
    "group": "com.socdm.d.adgeneration",
    "module": "adg",
    "version": "2.33.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "adg-2.33.0.aar",
          "url": "adg-2.33.0.aar",
          "size": 669329,
          "sha512": "40dcc98aeff5ef638b44ca7243ab729960f464fd5570ea28e7f7b1abd4018bcc21c910a334547b7d760dd36dfbdf7ebc8a4b78ca6d2a602d6c7f7931afc49fbb",
          "sha256": "ff432fd3ef2e452b4c0a2f41bc95d0b8b80961a2785e64cc406cfd921331a01a",
          "sha1": "38c4da5080ba9cfa799cab8f8c6cd8f6bead95af",
          "md5": "afd66a2fa46db6ddce0e89e08532dd21"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "adg-2.33.0.aar",
          "url": "adg-2.33.0.aar",
          "size": 669329,
          "sha512": "40dcc98aeff5ef638b44ca7243ab729960f464fd5570ea28e7f7b1abd4018bcc21c910a334547b7d760dd36dfbdf7ebc8a4b78ca6d2a602d6c7f7931afc49fbb",
          "sha256": "ff432fd3ef2e452b4c0a2f41bc95d0b8b80961a2785e64cc406cfd921331a01a",
          "sha1": "38c4da5080ba9cfa799cab8f8c6cd8f6bead95af",
          "md5": "afd66a2fa46db6ddce0e89e08532dd21"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "adg-2.33.0-sources.jar",
          "url": "adg-2.33.0-sources.jar",
          "size": 435791,
          "sha512": "90e3c0fe925943493fbd00e1bbc882a113375048729b398f8b961d6bcf12439c6e905bf69240b247dcea5c426a3febd004e116cdbbb8aa438cf671dbcca063f3",
          "sha256": "a5b254f7918febfac299d75ca66de46051ae68b47686b72e03528e4fe0b03538",
          "sha1": "8bb39366fdf4e092d6cef95275353477fbc85838",
          "md5": "ce6a66976307fd6eeec18c83db2f189a"
        }
      ]
    }
  ]
}
