{
  "formatVersion": "1.1",
  "component": {
    "group": "com.socdm.d.adgeneration",
    "module": "adg",
    "version": "2.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "adg-2.28.0.aar",
          "url": "adg-2.28.0.aar",
          "size": 661738,
          "sha512": "2af20dff464cc9716b2bcc7f7c4e4ec6e903d3f40564edbb9603f85e0053d13c524b23fde60d74937f14935b13f592dc3e881955d33c1b507afcecdae0f4ac63",
          "sha256": "f89ef3e852395f5796f0cdf63daba029e20a640e1f667d75f50e98b1e2b0b838",
          "sha1": "eb65a0441339515aa36c14ccf7e7787cd8daee62",
          "md5": "67ab9faed4c2314324ce455a792c03fd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "adg-2.28.0.aar",
          "url": "adg-2.28.0.aar",
          "size": 661738,
          "sha512": "2af20dff464cc9716b2bcc7f7c4e4ec6e903d3f40564edbb9603f85e0053d13c524b23fde60d74937f14935b13f592dc3e881955d33c1b507afcecdae0f4ac63",
          "sha256": "f89ef3e852395f5796f0cdf63daba029e20a640e1f667d75f50e98b1e2b0b838",
          "sha1": "eb65a0441339515aa36c14ccf7e7787cd8daee62",
          "md5": "67ab9faed4c2314324ce455a792c03fd"
        }
      ]
    }
  ]
}
