{
  "formatVersion": "1.1",
  "component": {
    "group": "com.socdm.d.adgeneration",
    "module": "adg-maio-adapter",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adg-maio-adapter-1.1.0.aar",
          "url": "adg-maio-adapter-1.1.0.aar",
          "size": 21587,
          "sha512": "f46b842e3663ce2111c5ff3965b6b48c7f18c45372b42e7fd01e790663c6c24c07c95f17356393874c015272aa9f2521b9d3846d335a9b8f472245c5c78a94c6",
          "sha256": "924a214352deb187006fcf960c374448a3e8f06c22ba531f4cdfeb218b9a8d07",
          "sha1": "6c203925e06b8a51afc978795463e16964a25260",
          "md5": "b48262b33fb9574f2e3f7a49669ef651"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "adg-maio-adapter-1.1.0.aar",
          "url": "adg-maio-adapter-1.1.0.aar",
          "size": 21587,
          "sha512": "f46b842e3663ce2111c5ff3965b6b48c7f18c45372b42e7fd01e790663c6c24c07c95f17356393874c015272aa9f2521b9d3846d335a9b8f472245c5c78a94c6",
          "sha256": "924a214352deb187006fcf960c374448a3e8f06c22ba531f4cdfeb218b9a8d07",
          "sha1": "6c203925e06b8a51afc978795463e16964a25260",
          "md5": "b48262b33fb9574f2e3f7a49669ef651"
        }
      ]
    }
  ]
}
