{
  "formatVersion": "1.1",
  "component": {
    "group": "com.socdm.d.adgeneration",
    "module": "adg-admob-mediation",
    "version": "2.27.100",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "adg-admob-mediation-2.27.100.aar",
          "url": "adg-admob-mediation-2.27.100.aar",
          "size": 27604,
          "sha512": "aa7985512f0a53b81808ca1458bc7508f9031b8a9f5467f3e92ae05aa65b9b5139b1b38ed76371f9ea2d2219cbb9ebc55acd5fc11506ec7f09f20a1a4384c489",
          "sha256": "9174cce9cae33471288b325f9322b394420bfe4f39b953012098a7628d9944af",
          "sha1": "b82660be7ed9e3535ee0cb4b4e52ae6f2b04ccf9",
          "md5": "bb984e07764ebff5d7e8e172f2b7342c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.4.0"
          }
        },
        {
          "group": "com.socdm.d.adgeneration",
          "module": "adg",
          "version": {
            "requires": "2.27.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "adg-admob-mediation-2.27.100.aar",
          "url": "adg-admob-mediation-2.27.100.aar",
          "size": 27604,
          "sha512": "aa7985512f0a53b81808ca1458bc7508f9031b8a9f5467f3e92ae05aa65b9b5139b1b38ed76371f9ea2d2219cbb9ebc55acd5fc11506ec7f09f20a1a4384c489",
          "sha256": "9174cce9cae33471288b325f9322b394420bfe4f39b953012098a7628d9944af",
          "sha1": "b82660be7ed9e3535ee0cb4b4e52ae6f2b04ccf9",
          "md5": "bb984e07764ebff5d7e8e172f2b7342c"
        }
      ]
    }
  ]
}
