{
  "formatVersion": "1.1",
  "component": {
    "group": "com.socdm.d.adgeneration",
    "module": "adg",
    "version": "2.29.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "adg-2.29.0.aar",
          "url": "adg-2.29.0.aar",
          "size": 657774,
          "sha512": "1698d456956f655c03600646857731e13ec5a2e2b22a680bd0828f8a5c08cbcf467a29eb44c13828a1c1191e746f159cc979472398f41cb5c915b759a8beb401",
          "sha256": "6f68346298eab6d257e535040083c0de2e5184e856dded7089d622c1239ed724",
          "sha1": "9520b4801fcd16889e8569cf16d364d2fc969484",
          "md5": "59e692b0555128046251f43c4a3bf22e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "adg-2.29.0.aar",
          "url": "adg-2.29.0.aar",
          "size": 657774,
          "sha512": "1698d456956f655c03600646857731e13ec5a2e2b22a680bd0828f8a5c08cbcf467a29eb44c13828a1c1191e746f159cc979472398f41cb5c915b759a8beb401",
          "sha256": "6f68346298eab6d257e535040083c0de2e5184e856dded7089d622c1239ed724",
          "sha1": "9520b4801fcd16889e8569cf16d364d2fc969484",
          "md5": "59e692b0555128046251f43c4a3bf22e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "adg-2.29.0-sources.jar",
          "url": "adg-2.29.0-sources.jar",
          "size": 435425,
          "sha512": "17350c689303408f76d889e3b560bf6f7a7d31bb6b67e828da5979c5ab3624dbb9519d102660bb38b5f0302f76631079899f8f14e733d9cf8ce6441a2164351f",
          "sha256": "4df8918146639a920871c9b1c317c6202f55d53229ab5773907d59cf1420bfe2",
          "sha1": "84c24887c9a4248e8485dde13740d3b212f3711b",
          "md5": "47d66098680a113e7d91268f3a8fbb27"
        }
      ]
    }
  ]
}
