{
  "formatVersion": "1.1",
  "component": {
    "group": "com.socdm.d.adgeneration",
    "module": "adg-five-adapter",
    "version": "2.26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adg-five-adapter-2.26.0.aar",
          "url": "adg-five-adapter-2.26.0.aar",
          "size": 22656,
          "sha512": "a2d47d8c1f167fa525b7386d2e68cc3a62aa38b283e5c25117a0982d674cae3e5ecadc834b66ec9b38381a70afc7361310ca30f18cfdfe369d032044f876a0db",
          "sha256": "5e1e99d8eb73747ccfb3bba76d2f80189745593d3d4a950bdb108841b1db5c82",
          "sha1": "6da28abdd83f3542e5f655c24af8411424d3a016",
          "md5": "10da3a1489fc6ed3e7bd76ffddc91717"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.linecorp.adsnetwork",
          "module": "fivead",
          "version": {
            "requires": "2.7.20240214"
          }
        }
      ],
      "files": [
        {
          "name": "adg-five-adapter-2.26.0.aar",
          "url": "adg-five-adapter-2.26.0.aar",
          "size": 22656,
          "sha512": "a2d47d8c1f167fa525b7386d2e68cc3a62aa38b283e5c25117a0982d674cae3e5ecadc834b66ec9b38381a70afc7361310ca30f18cfdfe369d032044f876a0db",
          "sha256": "5e1e99d8eb73747ccfb3bba76d2f80189745593d3d4a950bdb108841b1db5c82",
          "sha1": "6da28abdd83f3542e5f655c24af8411424d3a016",
          "md5": "10da3a1489fc6ed3e7bd76ffddc91717"
        }
      ]
    }
  ]
}
