{
  "formatVersion": "1.1",
  "component": {
    "group": "com.socdm.d.adgeneration",
    "module": "adg",
    "version": "2.27.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "adg-2.27.1.aar",
          "url": "adg-2.27.1.aar",
          "size": 604582,
          "sha512": "e4c68e4a66d0d7337cfdef2225e875644a072c33bb889a08645153eec7be26eecc62a2a1c447c64e8e5842ed23e25779911958c16e53eb9f171ded708fc61a8d",
          "sha256": "fe21d10ce748acc02e82f50ce981d8b93fa33164ba3ca8d151e3e74bc0528bf6",
          "sha1": "16ba5531372af597829a3207b28293c3b1cfbee0",
          "md5": "5c8d1c26c56628e1033d1c6467104b0c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "adg-2.27.1.aar",
          "url": "adg-2.27.1.aar",
          "size": 604582,
          "sha512": "e4c68e4a66d0d7337cfdef2225e875644a072c33bb889a08645153eec7be26eecc62a2a1c447c64e8e5842ed23e25779911958c16e53eb9f171ded708fc61a8d",
          "sha256": "fe21d10ce748acc02e82f50ce981d8b93fa33164ba3ca8d151e3e74bc0528bf6",
          "sha1": "16ba5531372af597829a3207b28293c3b1cfbee0",
          "md5": "5c8d1c26c56628e1033d1c6467104b0c"
        }
      ]
    }
  ]
}
