{
  "formatVersion": "1.1",
  "component": {
    "group": "com.socdm.d.adgeneration",
    "module": "adg-five-adapter",
    "version": "102.7.20240515.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adg-five-adapter-102.7.20240515.0.aar",
          "url": "adg-five-adapter-102.7.20240515.0.aar",
          "size": 25009,
          "sha512": "470e56cd8afd98bf539642ad57d970cb6225fdbab83df8790ba35f0a8e1e140f596e44bc1d08a0e1f4e16290c1a048911db05c13f5ec1854d250f731b2f69105",
          "sha256": "b1f0206e61830c937963dae57e774fb7249bec3a4489efc9de7babad41fe5539",
          "sha1": "69650123a16fdc702aeacf59c6c1c578899ca904",
          "md5": "b18b854c17ff8e9002f39cd94e18e021"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.linecorp.adsnetwork",
          "module": "fivead",
          "version": {
            "requires": "2.7.20240515"
          }
        }
      ],
      "files": [
        {
          "name": "adg-five-adapter-102.7.20240515.0.aar",
          "url": "adg-five-adapter-102.7.20240515.0.aar",
          "size": 25009,
          "sha512": "470e56cd8afd98bf539642ad57d970cb6225fdbab83df8790ba35f0a8e1e140f596e44bc1d08a0e1f4e16290c1a048911db05c13f5ec1854d250f731b2f69105",
          "sha256": "b1f0206e61830c937963dae57e774fb7249bec3a4489efc9de7babad41fe5539",
          "sha1": "69650123a16fdc702aeacf59c6c1c578899ca904",
          "md5": "b18b854c17ff8e9002f39cd94e18e021"
        }
      ]
    }
  ]
}
